service:
  name: next-serverless-boilerplate

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.secrets.NODE_ENV}
  region: us-west-1
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}

functions:
  server:
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
  
plugins:
  - serverless-apigw-binary
  # - serverless-domain-manager
  - serverless-webpack

custom:
  secrets: ${file(secrets.json)}
  webpack:
    packager: 'yarn'
    package:
      individually: true
    includeModules:
      forceInclude:
        - axios
      forceExclude:
        - aws-sdk
  apigwBinary:
    types:
      - '*/*'
  # customDomain:
  #   domainName: ${self:custom.secrets.DOMAIN}
  #   basePath: ''
  #   stage: ${self:custom.secrets.NODE_ENV}
  #   createRoute53Record: true
    # endpointType: 'regional'
    # if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`